{{- if (include "immich.rclone.enabled" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immich.fullname" . }}-rclone
  labels:
    {{- include "immich.serverLabels" . | nindent 4 }}
type: Opaque
data:
  RCLONE_S3_ACCESS_KEY_ID: {{ .Values.server.rclone.s3.accessKey | b64enc }}
  RCLONE_S3_SECRET_ACCESS_KEY: {{ .Values.server.rclone.s3.secretKey | b64enc }}
{{- end }}
