apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "immich.fullname" . }}-machine-learning
  labels:
    {{- include "immich.machineLearningLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.machineLearning.replicaCount }}
  strategy:
    type: {{ .Values.machineLearning.deploymentStrategy }}
  selector:
    matchLabels:
      {{- include "immich.machineLearningSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "immich.machineLearningLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.machineLearning.image.repository }}:{{
            .Values.machineLearning.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.machineLearning.image.pullPolicy }}
          env:
            - name: HF_XET_CACHE
              value: /cache/huggingface-xet
            - name: MPLCONFIGDIR
              value: /cache/matplotlib-config
            - name: TRANSFORMERS_CACHE
              value: /cache
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: {{ .Values.machineLearning.startupProbeFailureThreshold }}
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          {{- with .Values.machineLearning.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: cache
              mountPath: /cache
      volumes:
        - name: cache
          {{- if .Values.machineLearning.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "immich.machineLearning.persistence.claimName" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.machineLearning.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.machineLearning.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.machineLearning.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
